name: gastos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  fl_chart: ^1.1.1
  mongo_dart: ^0.10.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  printing: ^5.12.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  csv: ^6.0.0
  file_picker: ^10.3.6
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  local_auth: ^3.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
